name: Bug Report
description: Report a non-compatibility bug (crash, install issue, etc.)
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - OS:
        - bun:
        - `make doctor` output:
